#!/usr/bin/env bash

echo "----------------------------------------------------------------------"
printf '%-59s%-11s\n' 'TEST' 'STATUS'
echo "======================================================================"

success=true
for i
do
    printf "%-59s" $i
    if sh -c "valgrind --log-file=$i.mem --leak-check=full --error-exitcode=42 $i > $i.log 2>&1" 2>/dev/null
    then
        echo PASS
    else
        if [ $? -eq 42 ]; then
            echo MEMORY LEAK, see "$i.mem"
            success=false
        else
            echo FAIL
            success=false
        fi
    fi
done

echo "----------------------------------------------------------------------"

if $success; then
    printf '%+70s\n' 'ALL TESTS PASSED.'
    exit 0
fi

printf '%+70s' 'TESTS FAILED.'
exit 1
