name: CI

on:
  pull_request:
    branches: [ master ]

  push:

jobs:
  build-linux-cabal:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.4'

    - uses: actions/cache@v2
      name: Cache ~/.stack and .stack-work
      with:
        path: |
          ~/.cabal
          ~/.ghc
          dist-newstyle
        key: ${{ runner.os }}-cabal

    - run: cabal update

    - run: cabal build

    - run: cabal test

    - run: cabal exec -- make -C crt_test

    - run: cabal exec -- make -C test/test_compiled
